### ISSUE TITLE
tests location

### ISSUE THREAD

**Issue by jbok4** [learn-co-curriculum/javascript-intro-to-debugging#15]
tests are located in the intro-test.js

**Comment by aturkewi** [comment]
Hey @jbok4 thanks for raising an issue, but I'm not sure I understand. What is the issue exactly?
Could you please post what commands you're running or what it is you are doing, what you expected to happen, and what actually happened?

Thanks!

**Comment by jbok4** [comment]
hey Avidor,

There is a typo in the instructions index-test.js instead of intro-test.js
In the instructions it states...

Running the test suite

We've got a test suite set up for you, and we're going to walk through how
to run Mocha tests to correct our code. The tests are located in
test/index-test.js

On Tue, Nov 15, 2016 at 11:19 AM, Avidor Turkewitz <notifications@github.com

**Comment by aturkewi** [comment]
Fixed in PR #16
