### ISSUE TITLE
Not able to run tests 

### ISSUE THREAD

**Issue by jenjiyi** [learn-co-curriculum/javascript-intro-to-debugging#9]
`learn` command returns

`This directory doesn't appear to have any specs in it.`

I double checked my directory and checked my learn status and everything seems OK. Are there dependencies not listed for OSx?

**Comment by AnnJohn** [comment]
@jenjiyi this looks like a product issue. Could you email support@learn.co or file a bug report? thanks.

**Comment by jenjiyi** [comment]
Sure, will do.
